[2023-06-09 23:29:10,926] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: leads_raw_data_full_load_pipeline.parquet_to_postgres scheduled__2023-05-01T00:00:00+00:00 [queued]>
[2023-06-09 23:29:11,181] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: leads_raw_data_full_load_pipeline.parquet_to_postgres scheduled__2023-05-01T00:00:00+00:00 [queued]>
[2023-06-09 23:29:11,182] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 23:29:11,183] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 23:29:11,184] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 23:29:11,300] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): parquet_to_postgres> on 2023-05-01 00:00:00+00:00
[2023-06-09 23:29:11,340] {standard_task_runner.py:52} INFO - Started process 26972 to run task
[2023-06-09 23:29:11,348] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'leads_raw_data_full_load_pipeline', 'parquet_to_postgres', 'scheduled__2023-05-01T00:00:00+00:00', '--job-id', '553', '--raw', '--subdir', 'DAGS_FOLDER/leads_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpuzg945vf', '--error-file', '/tmp/tmpiyyo9a7g']
[2023-06-09 23:29:11,370] {standard_task_runner.py:77} INFO - Job 553: Subtask parquet_to_postgres
[2023-06-09 23:29:11,684] {logging_mixin.py:109} INFO - Running <TaskInstance: leads_raw_data_full_load_pipeline.parquet_to_postgres scheduled__2023-05-01T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 23:29:12,330] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=leads_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=parquet_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T00:00:00+00:00
[2023-06-09 23:29:16,036] {logging_mixin.py:109} INFO - Error loading Parquet file into PostgreSQL: (psycopg2.errors.UndefinedTable) table "leads_sft" does not exist

[SQL: 
DROP TABLE leads_sft]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2023-06-09 23:29:16,037] {python.py:152} INFO - Done. Returned value was: None
[2023-06-09 23:29:16,972] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=leads_raw_data_full_load_pipeline, task_id=parquet_to_postgres, execution_date=20230501T000000, start_date=20230609T232910, end_date=20230609T232916
[2023-06-09 23:29:17,390] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-06-09 23:29:17,879] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
