[2023-06-09 15:08:31,885] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_21.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 15:08:31,987] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_21.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 15:08:31,989] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:08:31,995] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:08:31,996] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:08:32,143] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_21.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 15:08:32,171] {standard_task_runner.py:52} INFO - Started process 1473 to run task
[2023-06-09 15:08:32,199] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_21.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmp72k4t1be', '--error-file', '/tmp/tmp56aps8ex']
[2023-06-09 15:08:32,228] {standard_task_runner.py:77} INFO - Job 22: Subtask load_sftp_datadata_21.csv
[2023-06-09 15:08:32,516] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_21.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:08:32,853] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_21.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 15:08:32,901] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:08:33,046] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:08:33,242] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_21.csv, execution_date=20230608T000000, start_date=20230609T150831, end_date=20230609T150833
[2023-06-09 15:08:35,588] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 15:22:15,275] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_21.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:15,500] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_21.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:15,518] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:15,519] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:22:15,520] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:15,680] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_21.csv> on 2023-06-09 15:20:24.730543+00:00
[2023-06-09 15:22:15,694] {standard_task_runner.py:52} INFO - Started process 3448 to run task
[2023-06-09 15:22:15,722] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_21.csv', 'manual__2023-06-09T15:20:24.730543+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpjmc8yf9q', '--error-file', '/tmp/tmpqkyu7lgl']
[2023-06-09 15:22:15,753] {standard_task_runner.py:77} INFO - Job 70: Subtask load_sftp_datadata_21.csv
[2023-06-09 15:22:16,034] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_21.csv manual__2023-06-09T15:20:24.730543+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:22:16,402] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_21.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T15:20:24.730543+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T15:20:24.730543+00:00
[2023-06-09 15:22:16,482] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:22:16,695] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:22:16,913] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_21.csv, execution_date=20230609T152024, start_date=20230609T152215, end_date=20230609T152216
[2023-06-09 15:22:19,347] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 16:52:33,423] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_21.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:33,871] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_21.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:33,875] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:33,895] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 16:52:33,895] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:34,120] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_21.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 16:52:34,171] {standard_task_runner.py:52} INFO - Started process 840 to run task
[2023-06-09 16:52:34,215] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_21.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmppv9q2cqo', '--error-file', '/tmp/tmp5ujrg_6f']
[2023-06-09 16:52:34,270] {standard_task_runner.py:77} INFO - Job 32: Subtask load_sftp_datadata_21.csv
[2023-06-09 16:52:35,107] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_21.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 16:52:36,162] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_21.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 16:52:36,356] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '/opt/data/temp_files/None'
[2023-06-09 16:52:36,769] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 16:52:37,244] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_21.csv, execution_date=20230608T000000, start_date=20230609T165233, end_date=20230609T165237
[2023-06-09 16:52:41,320] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
