[2023-06-09 15:08:33,922] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_16.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 15:08:34,054] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_16.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 15:08:34,056] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:08:34,059] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:08:34,061] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:08:34,257] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_16.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 15:08:34,288] {standard_task_runner.py:52} INFO - Started process 1495 to run task
[2023-06-09 15:08:34,287] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_16.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmp_xxzauf3', '--error-file', '/tmp/tmpsquiuk9t']
[2023-06-09 15:08:34,314] {standard_task_runner.py:77} INFO - Job 31: Subtask load_sftp_datadata_16.csv
[2023-06-09 15:08:34,579] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_16.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:08:35,053] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_16.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 15:08:35,130] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:08:35,312] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:08:35,622] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_16.csv, execution_date=20230608T000000, start_date=20230609T150833, end_date=20230609T150835
[2023-06-09 15:08:39,171] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 15:22:16,064] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_16.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:16,224] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_16.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:16,228] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:16,230] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:22:16,231] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:16,449] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_16.csv> on 2023-06-09 15:20:24.730543+00:00
[2023-06-09 15:22:16,478] {standard_task_runner.py:52} INFO - Started process 3457 to run task
[2023-06-09 15:22:16,523] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_16.csv', 'manual__2023-06-09T15:20:24.730543+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpt5ok92ry', '--error-file', '/tmp/tmpgxnm6zhf']
[2023-06-09 15:22:16,563] {standard_task_runner.py:77} INFO - Job 71: Subtask load_sftp_datadata_16.csv
[2023-06-09 15:22:17,048] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_16.csv manual__2023-06-09T15:20:24.730543+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:22:17,456] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_16.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T15:20:24.730543+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T15:20:24.730543+00:00
[2023-06-09 15:22:17,516] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:22:17,618] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:22:17,868] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_16.csv, execution_date=20230609T152024, start_date=20230609T152216, end_date=20230609T152217
[2023-06-09 15:22:22,247] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 16:52:33,746] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_16.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:34,114] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_16.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:34,116] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:34,118] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 16:52:34,122] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:34,409] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_16.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 16:52:34,484] {standard_task_runner.py:52} INFO - Started process 842 to run task
[2023-06-09 16:52:34,519] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_16.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpjg8i19f4', '--error-file', '/tmp/tmphcmj06gm']
[2023-06-09 16:52:34,583] {standard_task_runner.py:77} INFO - Job 31: Subtask load_sftp_datadata_16.csv
[2023-06-09 16:52:35,243] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_16.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 16:52:36,053] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_16.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 16:52:36,219] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '/opt/data/temp_files/None'
[2023-06-09 16:52:36,607] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 16:52:37,089] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_16.csv, execution_date=20230608T000000, start_date=20230609T165233, end_date=20230609T165237
[2023-06-09 16:52:40,351] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
