[2023-06-09 23:26:59,721] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: leads_raw_data_full_load_pipeline.parquet_to_postgres scheduled__2023-03-10T00:00:00+00:00 [queued]>
[2023-06-09 23:26:59,884] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: leads_raw_data_full_load_pipeline.parquet_to_postgres scheduled__2023-03-10T00:00:00+00:00 [queued]>
[2023-06-09 23:26:59,890] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 23:26:59,891] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 23:26:59,892] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 23:26:59,977] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): parquet_to_postgres> on 2023-03-10 00:00:00+00:00
[2023-06-09 23:26:59,993] {standard_task_runner.py:52} INFO - Started process 25892 to run task
[2023-06-09 23:27:00,013] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'leads_raw_data_full_load_pipeline', 'parquet_to_postgres', 'scheduled__2023-03-10T00:00:00+00:00', '--job-id', '500', '--raw', '--subdir', 'DAGS_FOLDER/leads_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpb0wq6e1f', '--error-file', '/tmp/tmpdc3ij9wb']
[2023-06-09 23:27:00,041] {standard_task_runner.py:77} INFO - Job 500: Subtask parquet_to_postgres
[2023-06-09 23:27:00,216] {logging_mixin.py:109} INFO - Running <TaskInstance: leads_raw_data_full_load_pipeline.parquet_to_postgres scheduled__2023-03-10T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 23:27:00,442] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=leads_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=parquet_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-03-10T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-10T00:00:00+00:00
[2023-06-09 23:27:05,367] {logging_mixin.py:109} INFO - Error loading Parquet file into PostgreSQL: (psycopg2.errors.UndefinedTable) table "leads_sft" does not exist

[SQL: 
DROP TABLE leads_sft]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2023-06-09 23:27:05,368] {python.py:152} INFO - Done. Returned value was: None
[2023-06-09 23:27:05,780] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=leads_raw_data_full_load_pipeline, task_id=parquet_to_postgres, execution_date=20230310T000000, start_date=20230609T232659, end_date=20230609T232705
[2023-06-09 23:27:06,079] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-06-09 23:27:06,439] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
