[2023-06-09 15:08:36,182] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_15.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 15:08:36,454] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_15.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 15:08:36,461] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:08:36,463] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:08:36,463] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:08:36,682] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_15.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 15:08:36,721] {standard_task_runner.py:52} INFO - Started process 1539 to run task
[2023-06-09 15:08:36,728] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_15.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpn6ke8qc6', '--error-file', '/tmp/tmpxfjnzhoq']
[2023-06-09 15:08:36,746] {standard_task_runner.py:77} INFO - Job 35: Subtask load_sftp_datadata_15.csv
[2023-06-09 15:08:37,216] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_15.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:08:37,725] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_15.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 15:08:37,838] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:08:37,946] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:08:38,193] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_15.csv, execution_date=20230608T000000, start_date=20230609T150836, end_date=20230609T150838
[2023-06-09 15:08:40,827] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 15:22:17,419] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_15.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:17,570] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_15.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:17,594] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:17,600] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:22:17,604] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:17,834] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_15.csv> on 2023-06-09 15:20:24.730543+00:00
[2023-06-09 15:22:17,873] {standard_task_runner.py:52} INFO - Started process 3475 to run task
[2023-06-09 15:22:17,900] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_15.csv', 'manual__2023-06-09T15:20:24.730543+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmp86bwc_59', '--error-file', '/tmp/tmp1hnkuzof']
[2023-06-09 15:22:17,928] {standard_task_runner.py:77} INFO - Job 73: Subtask load_sftp_datadata_15.csv
[2023-06-09 15:22:18,528] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_15.csv manual__2023-06-09T15:20:24.730543+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:22:19,215] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_15.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T15:20:24.730543+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T15:20:24.730543+00:00
[2023-06-09 15:22:19,379] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:22:19,646] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:22:19,885] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_15.csv, execution_date=20230609T152024, start_date=20230609T152217, end_date=20230609T152219
[2023-06-09 15:22:22,369] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 16:52:34,027] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_15.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:34,383] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_15.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:34,385] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:34,385] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 16:52:34,386] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:34,642] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_15.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 16:52:34,729] {standard_task_runner.py:52} INFO - Started process 844 to run task
[2023-06-09 16:52:34,820] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_15.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpe4_ea7ev', '--error-file', '/tmp/tmppuh34tem']
[2023-06-09 16:52:34,930] {standard_task_runner.py:77} INFO - Job 29: Subtask load_sftp_datadata_15.csv
[2023-06-09 16:52:35,826] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_15.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 16:52:36,770] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_15.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 16:52:36,980] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '/opt/data/temp_files/None'
[2023-06-09 16:52:37,185] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 16:52:37,430] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_15.csv, execution_date=20230608T000000, start_date=20230609T165234, end_date=20230609T165237
[2023-06-09 16:52:41,713] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
