[2023-06-09 23:26:03,998] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: leads_raw_data_full_load_pipeline.parquet_to_postgres scheduled__2023-02-12T00:00:00+00:00 [queued]>
[2023-06-09 23:26:04,219] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: leads_raw_data_full_load_pipeline.parquet_to_postgres scheduled__2023-02-12T00:00:00+00:00 [queued]>
[2023-06-09 23:26:04,222] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 23:26:04,228] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 23:26:04,230] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 23:26:04,400] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): parquet_to_postgres> on 2023-02-12 00:00:00+00:00
[2023-06-09 23:26:04,422] {standard_task_runner.py:52} INFO - Started process 25417 to run task
[2023-06-09 23:26:04,430] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'leads_raw_data_full_load_pipeline', 'parquet_to_postgres', 'scheduled__2023-02-12T00:00:00+00:00', '--job-id', '476', '--raw', '--subdir', 'DAGS_FOLDER/leads_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmph4cab166', '--error-file', '/tmp/tmp1fz20fiy']
[2023-06-09 23:26:04,443] {standard_task_runner.py:77} INFO - Job 476: Subtask parquet_to_postgres
[2023-06-09 23:26:04,647] {logging_mixin.py:109} INFO - Running <TaskInstance: leads_raw_data_full_load_pipeline.parquet_to_postgres scheduled__2023-02-12T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 23:26:05,001] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=leads_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=parquet_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-02-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-12T00:00:00+00:00
[2023-06-09 23:26:07,709] {logging_mixin.py:109} INFO - Error loading Parquet file into PostgreSQL: (psycopg2.errors.UndefinedTable) table "leads_sft" does not exist

[SQL: 
DROP TABLE leads_sft]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2023-06-09 23:26:07,712] {python.py:152} INFO - Done. Returned value was: None
[2023-06-09 23:26:07,809] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=leads_raw_data_full_load_pipeline, task_id=parquet_to_postgres, execution_date=20230212T000000, start_date=20230609T232604, end_date=20230609T232607
[2023-06-09 23:26:07,962] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-06-09 23:26:08,188] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
