[2023-06-09 23:27:31,480] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: leads_raw_data_full_load_pipeline.parquet_to_postgres scheduled__2023-03-23T00:00:00+00:00 [queued]>
[2023-06-09 23:27:31,694] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: leads_raw_data_full_load_pipeline.parquet_to_postgres scheduled__2023-03-23T00:00:00+00:00 [queued]>
[2023-06-09 23:27:31,695] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 23:27:31,696] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 23:27:31,697] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 23:27:31,798] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): parquet_to_postgres> on 2023-03-23 00:00:00+00:00
[2023-06-09 23:27:31,812] {standard_task_runner.py:52} INFO - Started process 26163 to run task
[2023-06-09 23:27:31,836] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'leads_raw_data_full_load_pipeline', 'parquet_to_postgres', 'scheduled__2023-03-23T00:00:00+00:00', '--job-id', '514', '--raw', '--subdir', 'DAGS_FOLDER/leads_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmp3y8ou2a6', '--error-file', '/tmp/tmpyclj7a_a']
[2023-06-09 23:27:31,850] {standard_task_runner.py:77} INFO - Job 514: Subtask parquet_to_postgres
[2023-06-09 23:27:32,070] {logging_mixin.py:109} INFO - Running <TaskInstance: leads_raw_data_full_load_pipeline.parquet_to_postgres scheduled__2023-03-23T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 23:27:32,502] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=leads_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=parquet_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-03-23T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-23T00:00:00+00:00
[2023-06-09 23:27:36,028] {logging_mixin.py:109} INFO - Error loading Parquet file into PostgreSQL: (psycopg2.errors.UndefinedTable) table "leads_sft" does not exist

[SQL: 
DROP TABLE leads_sft]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2023-06-09 23:27:36,029] {python.py:152} INFO - Done. Returned value was: None
[2023-06-09 23:27:37,403] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=leads_raw_data_full_load_pipeline, task_id=parquet_to_postgres, execution_date=20230323T000000, start_date=20230609T232731, end_date=20230609T232737
[2023-06-09 23:27:37,781] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-06-09 23:27:38,328] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
