[2023-06-09 15:08:34,901] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_20.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 15:08:35,177] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_20.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 15:08:35,186] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:08:35,210] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:08:35,220] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:08:35,417] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_20.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 15:08:35,434] {standard_task_runner.py:52} INFO - Started process 1519 to run task
[2023-06-09 15:08:35,473] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_20.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpsamgafu0', '--error-file', '/tmp/tmpceyjdpnx']
[2023-06-09 15:08:35,508] {standard_task_runner.py:77} INFO - Job 32: Subtask load_sftp_datadata_20.csv
[2023-06-09 15:08:36,048] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_20.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:08:36,447] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_20.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 15:08:36,513] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:08:36,675] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:08:36,929] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_20.csv, execution_date=20230608T000000, start_date=20230609T150834, end_date=20230609T150836
[2023-06-09 15:08:39,742] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 15:22:33,934] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_20.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:33,998] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_20.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:34,000] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:34,002] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:22:34,003] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:34,052] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_20.csv> on 2023-06-09 15:20:24.730543+00:00
[2023-06-09 15:22:34,064] {standard_task_runner.py:52} INFO - Started process 3598 to run task
[2023-06-09 15:22:34,079] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_20.csv', 'manual__2023-06-09T15:20:24.730543+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpzgqlsv37', '--error-file', '/tmp/tmp6c64z22g']
[2023-06-09 15:22:34,088] {standard_task_runner.py:77} INFO - Job 90: Subtask load_sftp_datadata_20.csv
[2023-06-09 15:22:34,271] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_20.csv manual__2023-06-09T15:20:24.730543+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:22:34,416] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_20.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T15:20:24.730543+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T15:20:24.730543+00:00
[2023-06-09 15:22:34,442] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:22:34,496] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:22:34,554] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_20.csv, execution_date=20230609T152024, start_date=20230609T152233, end_date=20230609T152234
[2023-06-09 15:22:34,660] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 16:52:35,617] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_20.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:36,097] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_20.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:36,099] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:36,113] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 16:52:36,116] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:36,495] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_20.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 16:52:36,566] {standard_task_runner.py:52} INFO - Started process 880 to run task
[2023-06-09 16:52:36,599] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_20.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpvpsug5gy', '--error-file', '/tmp/tmps6kuqu3i']
[2023-06-09 16:52:36,644] {standard_task_runner.py:77} INFO - Job 34: Subtask load_sftp_datadata_20.csv
[2023-06-09 16:52:37,531] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_20.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 16:52:38,245] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_20.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 16:52:38,281] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '/opt/data/temp_files/None'
[2023-06-09 16:52:38,417] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 16:52:38,579] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_20.csv, execution_date=20230608T000000, start_date=20230609T165235, end_date=20230609T165238
[2023-06-09 16:52:42,110] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
