[2023-06-09 23:28:28,871] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: leads_raw_data_full_load_pipeline.parquet_to_postgres scheduled__2023-04-14T00:00:00+00:00 [queued]>
[2023-06-09 23:28:29,007] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: leads_raw_data_full_load_pipeline.parquet_to_postgres scheduled__2023-04-14T00:00:00+00:00 [queued]>
[2023-06-09 23:28:29,010] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 23:28:29,012] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 23:28:29,013] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 23:28:30,505] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): parquet_to_postgres> on 2023-04-14 00:00:00+00:00
[2023-06-09 23:28:30,571] {standard_task_runner.py:52} INFO - Started process 26638 to run task
[2023-06-09 23:28:30,665] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'leads_raw_data_full_load_pipeline', 'parquet_to_postgres', 'scheduled__2023-04-14T00:00:00+00:00', '--job-id', '536', '--raw', '--subdir', 'DAGS_FOLDER/leads_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpu8rvoh0e', '--error-file', '/tmp/tmpv7tlwgpd']
[2023-06-09 23:28:30,730] {standard_task_runner.py:77} INFO - Job 536: Subtask parquet_to_postgres
[2023-06-09 23:28:31,118] {logging_mixin.py:109} INFO - Running <TaskInstance: leads_raw_data_full_load_pipeline.parquet_to_postgres scheduled__2023-04-14T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 23:28:31,801] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=leads_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=parquet_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-14T00:00:00+00:00
[2023-06-09 23:28:38,442] {logging_mixin.py:109} INFO - Error loading Parquet file into PostgreSQL: (psycopg2.errors.UndefinedTable) relation "leads_sft" does not exist
LINE 1: INSERT INTO leads_sft ("lead_UUID", phone_hash, email_hash) ...
                    ^

[SQL: INSERT INTO leads_sft ("lead_UUID", phone_hash, email_hash) VALUES (%(lead_UUID)s, %(phone_hash)s, %(email_hash)s)]
[parameters: ({'lead_UUID': 'c437ece50c0163479b180de9c217179bfed94e7d', 'phone_hash': '6e5345441aaeb5816ee08728681bbb5e18cbf365', 'email_hash': '3b7c33e84ea3ae8b249dc1e1578fc84cb4047ac4'}, {'lead_UUID': 'a63091da1b296757b868d30d6e5496bf48d86092', 'phone_hash': '8f2055fe6a78a8136b5e62e82d6b54b00d5c6ef9', 'email_hash': '137ac7f6012cc1165ccff9348abe55bb5fe86713'}, {'lead_UUID': 'e46c85a2bc8d1b5e5b68bfb719e9937d0f3cc621', 'phone_hash': '1083783d9c2c0f1ef84afbb3bded2b584ee683b8', 'email_hash': '240d374607278abc2823835fefe65f1d8cd50ec8'}, {'lead_UUID': '17a3b405290ae84377971e4efe8a0a6df9e85398', 'phone_hash': '262cf77e45bd889545b902eae7d21284b53e3dbc', 'email_hash': '77bd00d77b006ec1d92e855e8a480a78b4ac50b2'}, {'lead_UUID': '91fb6609d875f59b126dc760cccba3c9ce7b8910', 'phone_hash': 'f5a06e81bf514b38e5e5ffc3c4ba0c3ff4e65adf', 'email_hash': 'b417026cce185454e4a1bd493b0846f503d95d17'}, {'lead_UUID': 'be711223028df29045f4eceb50f842cf98eeb855', 'phone_hash': 'dcc6dc12d351803a5aa0b363425609a8a2f31fbb', 'email_hash': '9ace8905ba40aa18db1085b0b9423e5637d82f7b'}, {'lead_UUID': 'd5035e46852a9f516e5355ba40ed77c03340b187', 'phone_hash': 'a6580457df3c4105077f1fb54c4189d623c8ff9d', 'email_hash': '91bf175bba539940351d41ea61cb153ceca488d7'}, {'lead_UUID': '9a405225b09f0e6af524fca326d2558b10996dfa', 'phone_hash': 'c9162f8021288f162c4ce847eeef5c6f749f670d', 'email_hash': 'f5436a04877387a2264aa40126a5fa0d631241a0'}  ... displaying 10 of 4364 total bound parameter sets ...  {'lead_UUID': 'c67cfd97b9cb759c20bd8e71ee31f92b7db6e4f0', 'phone_hash': '6cc7168890973427e4094e89e89a53af843d0276', 'email_hash': 'db74d890b15b1400f19aefb3772054df76f54b55'}, {'lead_UUID': '374cdad3dec9596b23fc98dbadc7b6ac00a1367c', 'phone_hash': '062e303390014eb9f2ad9f806357ca32499acef2', 'email_hash': '66b6b210157226e8c946962556f127e8cf2c12bf'})]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2023-06-09 23:28:38,444] {python.py:152} INFO - Done. Returned value was: None
[2023-06-09 23:28:38,606] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=leads_raw_data_full_load_pipeline, task_id=parquet_to_postgres, execution_date=20230414T000000, start_date=20230609T232828, end_date=20230609T232838
[2023-06-09 23:28:38,990] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-06-09 23:28:39,375] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
