[2023-06-09 15:08:34,557] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_11.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 15:08:34,757] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_11.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 15:08:34,758] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:08:34,759] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:08:34,760] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:08:34,881] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_11.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 15:08:34,897] {standard_task_runner.py:52} INFO - Started process 1505 to run task
[2023-06-09 15:08:34,916] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_11.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmp8c7k1o6y', '--error-file', '/tmp/tmp8wvd_l0o']
[2023-06-09 15:08:34,946] {standard_task_runner.py:77} INFO - Job 33: Subtask load_sftp_datadata_11.csv
[2023-06-09 15:08:35,360] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_11.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:08:36,157] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_11.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 15:08:36,247] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:08:36,357] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:08:36,539] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_11.csv, execution_date=20230608T000000, start_date=20230609T150834, end_date=20230609T150836
[2023-06-09 15:08:39,455] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 15:22:18,242] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_11.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:18,542] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_11.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:18,543] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:18,544] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:22:18,545] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:18,762] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_11.csv> on 2023-06-09 15:20:24.730543+00:00
[2023-06-09 15:22:18,801] {standard_task_runner.py:52} INFO - Started process 3499 to run task
[2023-06-09 15:22:18,873] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_11.csv', 'manual__2023-06-09T15:20:24.730543+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmp5dtevksh', '--error-file', '/tmp/tmpwnkwdfcg']
[2023-06-09 15:22:18,935] {standard_task_runner.py:77} INFO - Job 75: Subtask load_sftp_datadata_11.csv
[2023-06-09 15:22:19,567] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_11.csv manual__2023-06-09T15:20:24.730543+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:22:20,283] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_11.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T15:20:24.730543+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T15:20:24.730543+00:00
[2023-06-09 15:22:20,375] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:22:20,735] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:22:21,088] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_11.csv, execution_date=20230609T152024, start_date=20230609T152218, end_date=20230609T152221
[2023-06-09 15:22:22,923] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 16:52:36,222] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_11.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:36,707] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_11.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:36,710] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:36,711] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 16:52:36,714] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:37,035] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_11.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 16:52:37,068] {standard_task_runner.py:52} INFO - Started process 882 to run task
[2023-06-09 16:52:37,129] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_11.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmp8lp9sa2y', '--error-file', '/tmp/tmp7yzufi0j']
[2023-06-09 16:52:37,204] {standard_task_runner.py:77} INFO - Job 35: Subtask load_sftp_datadata_11.csv
[2023-06-09 16:52:38,041] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_11.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 16:52:38,656] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_11.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 16:52:38,884] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '/opt/data/temp_files/None'
[2023-06-09 16:52:39,181] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 16:52:39,518] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_11.csv, execution_date=20230608T000000, start_date=20230609T165236, end_date=20230609T165239
[2023-06-09 16:52:42,482] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
