[2023-06-09 15:08:35,710] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_14.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 15:08:35,902] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_14.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 15:08:35,904] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:08:35,906] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:08:35,907] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:08:36,230] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_14.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 15:08:36,269] {standard_task_runner.py:52} INFO - Started process 1533 to run task
[2023-06-09 15:08:36,277] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_14.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpneirov94', '--error-file', '/tmp/tmpxqoami6d']
[2023-06-09 15:08:36,299] {standard_task_runner.py:77} INFO - Job 34: Subtask load_sftp_datadata_14.csv
[2023-06-09 15:08:36,611] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_14.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:08:37,203] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_14.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 15:08:37,289] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:08:37,389] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:08:37,510] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_14.csv, execution_date=20230608T000000, start_date=20230609T150835, end_date=20230609T150837
[2023-06-09 15:08:40,160] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 15:22:33,344] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_14.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:33,479] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_14.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:33,481] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:33,482] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:22:33,482] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:33,547] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_14.csv> on 2023-06-09 15:20:24.730543+00:00
[2023-06-09 15:22:33,557] {standard_task_runner.py:52} INFO - Started process 3591 to run task
[2023-06-09 15:22:33,577] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_14.csv', 'manual__2023-06-09T15:20:24.730543+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmphyq_ryt4', '--error-file', '/tmp/tmplsmkc8wo']
[2023-06-09 15:22:33,602] {standard_task_runner.py:77} INFO - Job 89: Subtask load_sftp_datadata_14.csv
[2023-06-09 15:22:33,803] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_14.csv manual__2023-06-09T15:20:24.730543+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:22:34,001] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_14.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T15:20:24.730543+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T15:20:24.730543+00:00
[2023-06-09 15:22:34,044] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:22:34,112] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:22:34,218] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_14.csv, execution_date=20230609T152024, start_date=20230609T152233, end_date=20230609T152234
[2023-06-09 15:22:34,376] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 16:52:28,509] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_14.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:28,913] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_14.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:28,916] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:28,920] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 16:52:28,927] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:29,247] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_14.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 16:52:29,309] {standard_task_runner.py:52} INFO - Started process 812 to run task
[2023-06-09 16:52:29,351] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_14.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpcm1ol6np', '--error-file', '/tmp/tmpbv9cfwin']
[2023-06-09 16:52:29,412] {standard_task_runner.py:77} INFO - Job 23: Subtask load_sftp_datadata_14.csv
[2023-06-09 16:52:29,788] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_14.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 16:52:30,439] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_14.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 16:52:30,552] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '/opt/data/temp_files/None'
[2023-06-09 16:52:30,809] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 16:52:31,249] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_14.csv, execution_date=20230608T000000, start_date=20230609T165228, end_date=20230609T165231
[2023-06-09 16:52:32,548] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
