[2023-06-09 15:22:32,079] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_5.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:32,172] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_5.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:32,174] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:32,175] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:22:32,176] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:32,298] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_5.csv> on 2023-06-09 15:20:24.730543+00:00
[2023-06-09 15:22:32,313] {standard_task_runner.py:52} INFO - Started process 3583 to run task
[2023-06-09 15:22:32,331] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_5.csv', 'manual__2023-06-09T15:20:24.730543+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmp8cxgj3bw', '--error-file', '/tmp/tmpgbn8pqpq']
[2023-06-09 15:22:32,355] {standard_task_runner.py:77} INFO - Job 85: Subtask load_sftp_datadata_5.csv
[2023-06-09 15:22:32,515] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_5.csv manual__2023-06-09T15:20:24.730543+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:22:32,743] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_5.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T15:20:24.730543+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T15:20:24.730543+00:00
[2023-06-09 15:22:32,785] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:22:32,875] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:22:32,984] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_5.csv, execution_date=20230609T152024, start_date=20230609T152232, end_date=20230609T152232
[2023-06-09 15:22:33,705] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 16:52:52,188] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_5.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:52,407] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_5.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:52,416] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:52,417] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 16:52:52,418] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:52,543] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_5.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 16:52:52,577] {standard_task_runner.py:52} INFO - Started process 988 to run task
[2023-06-09 16:52:52,598] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_5.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmp8t5tjchz', '--error-file', '/tmp/tmpspihlhgw']
[2023-06-09 16:52:52,618] {standard_task_runner.py:77} INFO - Job 43: Subtask load_sftp_datadata_5.csv
[2023-06-09 16:52:52,913] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_5.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 16:52:53,245] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_5.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 16:52:53,370] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '/opt/data/temp_files/None'
[2023-06-09 16:52:53,541] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 16:52:53,683] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_5.csv, execution_date=20230608T000000, start_date=20230609T165252, end_date=20230609T165253
[2023-06-09 16:52:54,345] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
