[2023-06-09 15:22:28,635] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_6.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:28,897] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_6.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:28,904] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:28,911] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:22:28,918] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:29,131] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_6.csv> on 2023-06-09 15:20:24.730543+00:00
[2023-06-09 15:22:29,174] {standard_task_runner.py:52} INFO - Started process 3571 to run task
[2023-06-09 15:22:29,201] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_6.csv', 'manual__2023-06-09T15:20:24.730543+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpnr4k5hfq', '--error-file', '/tmp/tmpiyna3s72']
[2023-06-09 15:22:29,246] {standard_task_runner.py:77} INFO - Job 79: Subtask load_sftp_datadata_6.csv
[2023-06-09 15:22:29,605] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_6.csv manual__2023-06-09T15:20:24.730543+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:22:30,047] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_6.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T15:20:24.730543+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T15:20:24.730543+00:00
[2023-06-09 15:22:30,114] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:22:30,299] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:22:30,541] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_6.csv, execution_date=20230609T152024, start_date=20230609T152228, end_date=20230609T152230
[2023-06-09 15:22:30,990] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 16:52:52,611] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_6.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:52,818] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_6.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:52,819] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:52,820] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 16:52:52,821] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:52,888] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_6.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 16:52:52,908] {standard_task_runner.py:52} INFO - Started process 992 to run task
[2023-06-09 16:52:52,929] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_6.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpm_mazg13', '--error-file', '/tmp/tmpq1qmurvm']
[2023-06-09 16:52:52,942] {standard_task_runner.py:77} INFO - Job 45: Subtask load_sftp_datadata_6.csv
[2023-06-09 16:52:53,209] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_6.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 16:52:53,584] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_6.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 16:52:53,645] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '/opt/data/temp_files/None'
[2023-06-09 16:52:53,739] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 16:52:53,899] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_6.csv, execution_date=20230608T000000, start_date=20230609T165252, end_date=20230609T165253
[2023-06-09 16:52:54,559] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
