[2023-06-09 15:22:32,991] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_9.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:33,085] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_9.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:33,090] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:33,093] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:22:33,094] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:33,216] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_9.csv> on 2023-06-09 15:20:24.730543+00:00
[2023-06-09 15:22:33,233] {standard_task_runner.py:52} INFO - Started process 3587 to run task
[2023-06-09 15:22:33,249] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_9.csv', 'manual__2023-06-09T15:20:24.730543+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpzwdpqdr6', '--error-file', '/tmp/tmp70bskmai']
[2023-06-09 15:22:33,259] {standard_task_runner.py:77} INFO - Job 87: Subtask load_sftp_datadata_9.csv
[2023-06-09 15:22:33,419] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_9.csv manual__2023-06-09T15:20:24.730543+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:22:33,573] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_9.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T15:20:24.730543+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T15:20:24.730543+00:00
[2023-06-09 15:22:33,604] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:22:33,698] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:22:33,827] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_9.csv, execution_date=20230609T152024, start_date=20230609T152233, end_date=20230609T152233
[2023-06-09 15:22:34,164] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 16:52:51,157] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_9.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:51,420] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_9.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:51,426] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:51,431] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 16:52:51,432] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:51,553] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_9.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 16:52:51,588] {standard_task_runner.py:52} INFO - Started process 979 to run task
[2023-06-09 16:52:51,599] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_9.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmp15vj81vz', '--error-file', '/tmp/tmpj8juil7b']
[2023-06-09 16:52:51,617] {standard_task_runner.py:77} INFO - Job 41: Subtask load_sftp_datadata_9.csv
[2023-06-09 16:52:51,863] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_9.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 16:52:52,290] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_9.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 16:52:52,381] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '/opt/data/temp_files/None'
[2023-06-09 16:52:52,500] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 16:52:52,744] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_9.csv, execution_date=20230608T000000, start_date=20230609T165251, end_date=20230609T165252
[2023-06-09 16:52:53,852] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
