[2023-06-09 15:22:33,161] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_7.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:33,241] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_7.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:33,242] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:33,243] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:22:33,244] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:33,329] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_7.csv> on 2023-06-09 15:20:24.730543+00:00
[2023-06-09 15:22:33,345] {standard_task_runner.py:52} INFO - Started process 3589 to run task
[2023-06-09 15:22:33,380] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_7.csv', 'manual__2023-06-09T15:20:24.730543+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpo51119_d', '--error-file', '/tmp/tmpxo3o_h1t']
[2023-06-09 15:22:33,400] {standard_task_runner.py:77} INFO - Job 88: Subtask load_sftp_datadata_7.csv
[2023-06-09 15:22:33,538] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_7.csv manual__2023-06-09T15:20:24.730543+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:22:33,739] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_7.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T15:20:24.730543+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T15:20:24.730543+00:00
[2023-06-09 15:22:33,802] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:22:33,943] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:22:34,025] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_7.csv, execution_date=20230609T152024, start_date=20230609T152233, end_date=20230609T152234
[2023-06-09 15:22:34,285] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 16:52:52,927] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_7.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:53,109] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_7.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:53,110] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:53,111] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 16:52:53,112] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:53,247] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_7.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 16:52:53,290] {standard_task_runner.py:52} INFO - Started process 994 to run task
[2023-06-09 16:52:53,297] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_7.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpo1igb9by', '--error-file', '/tmp/tmpa7pxu7hl']
[2023-06-09 16:52:53,314] {standard_task_runner.py:77} INFO - Job 46: Subtask load_sftp_datadata_7.csv
[2023-06-09 16:52:53,664] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_7.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 16:52:54,119] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_7.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 16:52:54,172] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '/opt/data/temp_files/None'
[2023-06-09 16:52:54,294] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 16:52:54,426] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_7.csv, execution_date=20230608T000000, start_date=20230609T165252, end_date=20230609T165254
[2023-06-09 16:52:54,921] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
